(ns wire.preds)

(defrecord Norm [norm-id implementation])
(defrecord CountsAs [abstract-fact context concrete-fact])
(defrecord Activation [norm wff])
(defrecord Expiration [norm wff])
(defrecord Maintenance [norm wff])
(defrecord Predicate [name argument-0 argument-1 argument-2 argument-3
                      argument-4 argument-5 argument-6 argument-7 argument-8 
                      argument-9 argument-10 argument-11 argument-12])
(defrecord AbstractFact [norm wff])
(defrecord Holds [wff substitution])
(defrecord HasClause [wff clause])
(defrecord Event [asserter content])
(defrecord Formula [content grounding])
(defrecord Instantiated [norm substitution])
(defrecord Abrogated [norm])
(defrecord NormInstanceInjected [norm substitution])
(defrecord Fulfilled [norm substitution])
(defrecord Violated [norm substitution])
(defrecord Repaired [norm substitution])
(defrecord SubsetEQ [subset superset])
(defrecord Repair [norm repair-norm])

(defrecord RestrictedCountsAs [abstract-fact context concrete-fact asserter])
(defrecord CountsAsPerm [abstract-fact context asserter])
