//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.07 at 04:10:50 PM CEST 
//


package net.sf.ictalive.monitoring.rules.drools.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://drools.org/drools-5.0}abstractConditionalElement"/>
 *         &lt;element ref="{http://drools.org/drools-5.0}not"/>
 *         &lt;element ref="{http://drools.org/drools-5.0}exists"/>
 *         &lt;element ref="{http://drools.org/drools-5.0}pattern"/>
 *         &lt;element ref="{http://drools.org/drools-5.0}eval"/>
 *         &lt;element ref="{http://drools.org/drools-5.0}forall"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "abstractConditionalElementOrNotOrExists"
})
@XmlRootElement(name = "lhs")
public class Lhs {

    @XmlElementRefs({
        @XmlElementRef(name = "eval", namespace = "http://drools.org/drools-5.0", type = JAXBElement.class),
        @XmlElementRef(name = "not", namespace = "http://drools.org/drools-5.0", type = Not.class),
        @XmlElementRef(name = "exists", namespace = "http://drools.org/drools-5.0", type = Exists.class),
        @XmlElementRef(name = "abstractConditionalElement", namespace = "http://drools.org/drools-5.0", type = JAXBElement.class),
        @XmlElementRef(name = "pattern", namespace = "http://drools.org/drools-5.0", type = Pattern.class),
        @XmlElementRef(name = "forall", namespace = "http://drools.org/drools-5.0", type = Forall.class)
    })
    protected List<Object> abstractConditionalElementOrNotOrExists;

    /**
     * Gets the value of the abstractConditionalElementOrNotOrExists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the abstractConditionalElementOrNotOrExists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAbstractConditionalElementOrNotOrExists().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link OrConditionalElement }{@code >}
     * {@link Not }
     * {@link Exists }
     * {@link JAXBElement }{@code <}{@link ConditionalElementType }{@code >}
     * {@link Pattern }
     * {@link JAXBElement }{@code <}{@link AndConditionalElement }{@code >}
     * {@link Forall }
     * 
     * 
     */
    public List<Object> getAbstractConditionalElementOrNotOrExists() {
        if (abstractConditionalElementOrNotOrExists == null) {
            abstractConditionalElementOrNotOrExists = new ArrayList<Object>();
        }
        return this.abstractConditionalElementOrNotOrExists;
    }

}
