//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.07 at 04:10:50 PM CEST 
//


package net.sf.ictalive.monitoring.rules.drools.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://drools.org/drools-5.0}import"/>
 *         &lt;element ref="{http://drools.org/drools-5.0}importfunction"/>
 *         &lt;element ref="{http://drools.org/drools-5.0}global"/>
 *         &lt;element ref="{http://drools.org/drools-5.0}function"/>
 *         &lt;element ref="{http://drools.org/drools-5.0}rule"/>
 *         &lt;element ref="{http://drools.org/drools-5.0}query"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "importOrImportfunctionOrGlobal"
})
@XmlRootElement(name = "package")
public class Package {

    @XmlElements({
        @XmlElement(name = "importfunction", type = Importfunction.class),
        @XmlElement(name = "query", type = Query.class),
        @XmlElement(name = "global", type = Global.class),
        @XmlElement(name = "function", type = Function.class),
        @XmlElement(name = "rule", type = Rule.class),
        @XmlElement(name = "import", type = Import.class)
    })
    protected List<Object> importOrImportfunctionOrGlobal;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the importOrImportfunctionOrGlobal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the importOrImportfunctionOrGlobal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImportOrImportfunctionOrGlobal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Importfunction }
     * {@link Query }
     * {@link Global }
     * {@link Function }
     * {@link Rule }
     * {@link Import }
     * 
     * 
     */
    public List<Object> getImportOrImportfunctionOrGlobal() {
        if (importOrImportfunctionOrGlobal == null) {
            importOrImportfunctionOrGlobal = new ArrayList<Object>();
        }
        return this.importOrImportfunctionOrGlobal;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
