//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.07 at 04:10:50 PM CEST 
//


package net.sf.ictalive.monitoring.rules.drools.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for restrictionElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="restrictionElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://drools.org/drools-5.0}literal-restriction"/>
 *         &lt;element ref="{http://drools.org/drools-5.0}variable-restriction"/>
 *         &lt;element ref="{http://drools.org/drools-5.0}return-value-restriction"/>
 *         &lt;element ref="{http://drools.org/drools-5.0}qualified-identifier-restriction"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "restrictionElementType", propOrder = {
    "literalRestrictionOrVariableRestrictionOrReturnValueRestriction"
})
@XmlSeeAlso({
    OrRestrictionConnective.class,
    AndRestrictionConnective.class,
    FieldConstraint.class
})
public class RestrictionElementType {

    @XmlElements({
        @XmlElement(name = "qualified-identifier-restriction", type = QualifiedIdentifierRestriction.class),
        @XmlElement(name = "variable-restriction", type = VariableRestriction.class),
        @XmlElement(name = "literal-restriction", type = LiteralRestriction.class),
        @XmlElement(name = "return-value-restriction", type = ReturnValueRestriction.class)
    })
    protected List<Object> literalRestrictionOrVariableRestrictionOrReturnValueRestriction;

    /**
     * Gets the value of the literalRestrictionOrVariableRestrictionOrReturnValueRestriction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the literalRestrictionOrVariableRestrictionOrReturnValueRestriction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLiteralRestrictionOrVariableRestrictionOrReturnValueRestriction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QualifiedIdentifierRestriction }
     * {@link VariableRestriction }
     * {@link LiteralRestriction }
     * {@link ReturnValueRestriction }
     * 
     * 
     */
    public List<Object> getLiteralRestrictionOrVariableRestrictionOrReturnValueRestriction() {
        if (literalRestrictionOrVariableRestrictionOrReturnValueRestriction == null) {
            literalRestrictionOrVariableRestrictionOrReturnValueRestriction = new ArrayList<Object>();
        }
        return this.literalRestrictionOrVariableRestrictionOrReturnValueRestriction;
    }

}
